### ISSUE TITLE
Controlling version of CUDA drivers installed

### ISSUE THREAD

**Issue by fcampagne** [NVIDIA/ansible-role-nvidia-driver#17]
Is it possible to specify the version to install? The documentation does not suggest that this is possible. 
Controlling the version is important for reproducibility. For instance, as of today, if I install the latest CUDA driver I will get CUDA 11.0, but I would need 10.2 for compatibility with the latest binary installation of pytorch (1.5.1 targets CUDA 10.2).

**Comment by ajdecon** [comment]
Yes, this is possible. You can specify the version by overridding the `nvidia_driver_package_version` variable with the package version you want to install.

Note that the version number here is the version of the NVIDIA driver package, and should match the version for the corresponding dpkg or rpm you will install with the system package manager. So, for example, on Ubuntu you could specify `nvidia_driver_package_version: 440.95.01-1` to install the `cuda-drivers` package of that version.

You can find the variables available for override in the `defaults/main.yml` file: https://github.com/NVIDIA/ansible-role-nvidia-driver/blob/master/defaults/main.yml

**Comment by FergusFettes** [comment]
this doesn't work (at least in the RHEL scripts). if you add ```nvidia_driver_package_version: 440``` it tries to install ```nvidia-driver-latest-dkms-440``` which doesn't exist, the install_redhat.yaml script needs to be updated I believe.

**Comment by mr-yaky** [comment]
Hi @FergusFettes, there is a fix for that issue if you still need it.

**Comment by ajdecon** [comment]
@FergusFettes : Note that the variable is `nvidia_driver_package_version`, which needs to specify the version number of the actual RPM package rather than the driver "branch version".

So, for example, you can specify `nvidia_driver_package_version: '440.95.01-1.el7'` which will install exactly that package version.

We do it this way so that you can specify a specific driver version (e.g. 440.95.01 vs 440.64.00), rather than just 440. We find the ability to specify the full version number useful because our users frequently want to pin a specific version across their infrastructure and control the versioning carefully.

**Comment by ajdecon** [comment]
Closing issue, please re-open if you see any issues when specifying the full package version desired.
