### ISSUE TITLE
Problem to install the NVIDIA drivers on CentOS 8

### ISSUE THREAD

**Issue by AlanSSKim** [NVIDIA/ansible-role-nvidia-driver#54]
Hi, 

I've got a problem to install the NVIDIA Driver on CentOS8. 

When installing for the first time, the latest version 495.29.05 was installed because the version was not specified.
and then I have specified the driver version in default/main.yml as shown below.

nvidia_driver_package_state: present
nvidia_driver_package_version: '470.57.02-1'
nvidia_driver_persistence_mode_on: yes

after that I ran the playbook, but the installation failed as follows:

TASK [nvidia.nvidia_driver : install driver packages RHEL/CentOS 8 and newer] *********************************************************************************
fatal: [gdp-glm-gpu001]: FAILED! => changed=false 
  msg: No group nvidia-driver:470.57.02-1 available.
  results: []

Even if I try changing it to multiple versions as shown below, it fails the same.

450.142.00
450.156.00-1
460.91.03-1
460.106.00-1
470.42.01-1
470.57.02-1

**Comment by ajdecon** [comment]
Due to changes in how the repositories are structured in RHEL/CentOS 8, the NVIDIA driver is now being installed as a [YUM module](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/introduction-to-modules_using-appstream) rather than as a list of specific packages. This also changes the versioning scheme.

PR #53 adds support for specifying the module version more explicitly, and updates the docs in order to make it a bit clearer how to specify versions in RHEL 8 and similar distros.

I expect this PR to get reviewed and merged early next year, as most of the relevant team members are off for the US holiday break.
